### ISSUE TITLE
Unit Tests for Groups, GroupPrivileges, NewsComments, News, Privileges model files

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#207]
Write unit test for:
- [x] Groups_model
- [x] GroupPrivileges_model
- [x] NewsComments_model
- [x] News_model
- [x] Privileges_model

**Comment by DishantK1807** [comment]
@kamishettysreeja25: I have already written test codes for all the files. There was a mix and match which I was doing while writing the tests. Please work on different issue as you working on this would've waste my time while you were refactoring.  Please work on the script and Travis first so that we could integrate the testing fast. I'll write test test codes as I've already writing them.
Thank you.

**Comment by DishantK1807** [comment]
Fixed here: #206
