### ISSUE TITLE
Unit Tests for Questions, Settings, User AngelTypes, UserGroups, User, WelcomeMessage model files

### ISSUE THREAD

**Issue by sreejakshetty** [fossasia/engelsystem#208]
Write unit test for:
- [x] Questions
- [x] Settings
- [x] User AngelTypes
- [x]  UserGroups
- [x] User
- [x] WelcomeMessage

**Comment by DishantK1807** [comment]
@kamishettysreeja25: I have already written test codes for all the files. There was a mix and match which I was doing while writing the tests. Please work on different issue as you working on this would've waste my time while you were refactoring. Please work on the script and Travis first so that we could integrate the testing fast. I'll write test test codes as I've already writing them.
Thank you

**Comment by sreejakshetty** [comment]
@DishantK1807 There were no issues created for these files. I worked on creating unit test in the milestone 1 https://github.com/fossasia/engelsystem/pull/42. It is easy for me to work on writing tests as I have already worked before and It will be not take much time to finish them. We need tests files to setup travis so it will be fast if we both work on and complete the issue.
Thank you.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: It'll be easy.  But I already worked on them while you were refactoring. You working on these would've waste a lot of mine time then.
Please find a different issue. 
Thank you

**Comment by DishantK1807** [comment]
@kamishettysreeja25: Thank you for creating the issues.

**Comment by sreejakshetty** [comment]
@dishantkhanna Welcome :)

**Comment by DishantK1807** [comment]
Fixed here: #206
