### ISSUE TITLE
Feature: User : Registration Form: Check if E-mail already exist 

### ISSUE THREAD

**Issue by DishantK1807** [fossasia/engelsystem#39]
The current configuration of the registration form does not check whether the E-mail exists in the system or not. User can do multiple registrations from the same E-mail account
![screenshot 14](https://cloud.githubusercontent.com/assets/7828295/15626990/1b70d68e-24f3-11e6-9a0c-07603f434e8e.png)

Will be adding a feature to check whether the E-mail account exists or not so that a user cannot do multiple registrations with same email account.

**Comment by DishantK1807** [comment]
![capture_email](https://cloud.githubusercontent.com/assets/7828295/15627029/3ede0e1a-24f4-11e6-951f-2e74ab721dc5.PNG)

Highlighted same email accounts in the database for different user registrations.

**Comment by DishantK1807** [comment]
![screenshot 15](https://cloud.githubusercontent.com/assets/7828295/15669826/ddc1c696-273f-11e6-865b-d11c450550f6.png)

Bug solved. Feature updated

**Comment by hpdang** [comment]
good job!

**Comment by vuhung** [comment]
Can you apply the same logic for other part of the code, that is, check if something, in this case - email, should (not) be duplicated.

**Comment by DishantK1807** [comment]
@vuhung : yes we can apply the same logic to the other fields ass well. What all other fields should I apply it on?

**Comment by hongquan** [comment]
I think it would better if you make these changes on _email_ column in MySQL database:
- Set `UNIQUE` attribute
- Set it case-insensitive, so that if quan@mail.com exists, Quan@mail.com will be rejected.

With this setting on database-level, anywhere you miss checking in PHP code, you still have the last barrier in database.

Setting this also make MySQL automatically index the email data, and make searching (`SELECT` query) faster.

If you make the changes, write it down as SQL commands in update.sql file.

**Comment by DishantK1807** [comment]
@hongquan : sure. I'll be creating a new issue for implementing it.
